# Generated by Django 4.2.1 on 2023-08-29 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='deleted',
            field=models.BooleanField(default=False, help_text='deleted flag', verbose_name='delted status'),
        ),
    ]
